version: "3.8"

service:
   web:
    image:
    container_name:
    ports:
    volumes:
    networks:
    enviroment:
    restart:
    depends_on:
      -db
      -app
    secrets:
    healthcheck:
    config:
    command:
    deploy:
      replicase:3
    
    

